-- 코드를 입력하세요
WITH SUB AS(
    SELECT BS.BOOK_ID, CATEGORY, B.AUTHOR_ID,
    (SUM(SALES) * PRICE) AS TOTAL
    FROM BOOK_SALES BS
    JOIN BOOK B
    ON BS.BOOK_ID = B.BOOK_ID
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
    GROUP BY BS.BOOK_ID, CATEGORY, AUTHOR_ID
)

SELECT S.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL) AS TOTAL_SALES
FROM SUB S
JOIN AUTHOR A
ON S.AUTHOR_ID = A.AUTHOR_ID
GROUP BY S.AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY S.AUTHOR_ID, CATEGORY DESC