-- 코드를 입력하세요
with SALE AS(
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM (
        SELECT *
        FROM BOOK_SALES
        where SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
    ) T
    GROUP BY BOOK_ID
), A AS(
    SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, 
    (TOTAL_SALES * PRICE) AS TOTAL_SALES
    from BOOK B
    JOIN AUTHOR A
    JOIN SALE S
    ON B.AUTHOR_ID = A.AUTHOR_ID AND B.BOOK_ID = S.BOOK_ID
    GROUP BY B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, PRICE
)
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY,
SUM(TOTAL_SALES) AS TOTAL_SALES
FROM A
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC