-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, 
CONCAT(Substring(TLNO,1,3), '-',  Substring(TLNO,4,4), '-', Substring(TLNO,8,12)) AS 전화번호
FROM (
    SELECT WRITER_ID, COUNT(WRITER_ID) AS QUANTITY
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
) T
JOIN USED_GOODS_USER UGU
ON T.WRITER_ID = UGU.USER_ID
WHERE QUANTITY >= 3
ORDER BY UGU.USER_ID DESC