-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(GENDER) AS USERS
FROM USER_INFO UI
JOIN (
    SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, SUM(SALES_AMOUNT) AS AMOUNT
    FROM ONLINE_SALE
    group by USER_ID, YEAR(SALES_DATE), MONTH(SALES_DATE)
) T
ON UI.USER_ID = T.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, gender
ORDER BY YEAR, MONTH, GENDER