with REGISTER as(
    select USER_ID
    from USER_INFO
    where YEAR(JOINED) = '2021'
), USER_COUNT AS (
SELECT DISTINCT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    O.USER_ID
FROM ONLINE_SALE O
JOIN REGISTER R
ON O.USER_ID = R.USER_ID 
) 

SELECT YEAR, MONTH,
    COUNT(*) AS PURCHASED_USERS,
    ROUND(COUNT(*) * 1.0/(SELECT COUNT(*) FROM REGISTER), 1) 
    AS PUCHASED_RATIO
from USER_COUNT
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
