-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM (SELECT *,
    SUM(PRICE) OVER (PARTITION BY WRITER_ID) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
) UGB
JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
WHERE TOTAL_SALES >= 700000
GROUP BY USER_ID, NICKNAME, TOTAL_SALES
ORDER BY TOTAL_SALES
