-- 코드를 입력하세요
WITH PRICE AS(
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
)
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER UGU 
JOIN PRICE P
ON P.WRITER_ID = UGU.USER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
