-- 코드를 입력하세요
WITH BUFFER AS (
    SELECT CAR_ID, 
    COUNT(*) AS TOTAL_RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
    GROUP BY CAR_ID
)
SELECT MONTH(START_DATE) AS MONTH, C.CAR_ID, COUNT(START_DATE) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN BUFFER B
ON C.CAR_ID = B.CAR_ID
WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31' AND B.TOTAL_RECORDS >= 5
GROUP BY MONTH, C.CAR_ID
ORDER BY MONTH, C.CAR_ID DESC