-- 코드를 작성해주세요
WITH MAX_DATA AS(
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
select MD.YEAR, (MD.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
from ECOLI_DATA ED
JOIN MAX_DATA MD
ON YEAR(DIFFERENTIATION_DATE) = MD.YEAR
ORDER BY MD.YEAR, YEAR_DEV