-- 코드를 작성해주세요
WITH MAXFISH AS (
    SELECT T.FISH_NAME, MAX(I.LENGTH) AS LENGTH
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO T
    ON I.FISH_TYPE = T.FISH_TYPE
    GROUP BY FISH_NAME
), MERGE AS(
    SELECT I.ID, T.FISH_NAME, LENGTH
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO T
    ON I.FISH_TYPE = T.FISH_TYPE
)
SELECT ID, M.FISH_NAME, M.LENGTH
FROM MAXFISH M
JOIN MERGE ME
ON M.FISH_NAME = ME.FISH_NAME
WHERE M.LENGTH = ME.LENGTH
ORDER BY ID