-- 코드를 작성해주세요
WITH SUB AS(
    SELECT ID, LENGTH, FISH_NAME,
    ROW_NUMBER() OVER
    (PARTITION BY F.FISH_TYPE ORDER BY LENGTH DESC) AS NA 
    FROM FISH_INFO F
    JOIN FISH_NAME_INFO FN
    ON F.FISH_TYPE = FN.FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM SUB
WHERE NA = 1
ORDER BY ID