-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM (
    SELECT INGREDIENT_TYPE, TOTAL_ORDER
    FROM FIRST_HALF FH
    JOIN ICECREAM_INFO II
    ON FH.FLAVOR = II.FLAVOR
) T
GROUP BY INGREDIENT_TYPE
    