-- 코드를 입력하세요
SELECT CATEGORY, SUM(TOTAL) AS TOTAL_SALES
FROM BOOK B
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL
    FROM BOOK_SALES
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
    GROUP BY BOOK_ID
) T
ON B.BOOK_ID = T.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY