-- 코드를 입력하세요
SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT *,
    MAX(PRICE) OVER(PARTITION BY CATEGORY) AS MAX_PRICE
    from FOOD_PRODUCT
    WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' 
    OR CATEGORY = '식용유'  
) T
WHERE MAX_PRICE = PRICE
ORDER BY MAX_PRICE DESC