-- 코드를 작성해주세요
WITH AVERAGE AS(
SELECT FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH, MAX(LENGTH) AS MAX_LENGTH, COUNT(FISH_TYPE) AS FISH_COUNT
FROM FISH_INFO
GROUP BY FISH_TYPE
)
SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM AVERAGE
WHERE AVG_LENGTH >= 33
ORDER BY FISH_TYPE