-- 코드를 입력하세요
WITH BUFFER AS(
    SELECT *, Substring(PRICE / 10000, 1, 1) * 10000 AS PRICE_GROUP
    FROM PRODUCT
)
SELECT PRICE_GROUP, COUNT(PRICE_GROUP) AS PRODUCTS
FROM BUFFER
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP